# Generated by Django 5.0.4 on 2024-05-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='slug',
            new_name='news_slug',
        ),
    ]
